#162949070 Users should receive a JWT on successful Registration
andela/ah-robotics pull request #9
Opened 2019-01-15 14:55 UTC by waracci

#### What does this PR do?

> Implement JWT upon user registration and add flake8 linting tool

#### Description of Task to be completed?

- Users should receive a `Json Web Token` on successful Registration, the token is used to authenticate the user on protected routes.
- add flake8 linting tool to ensure all code submitted conforms to pep8 Style Guide for Python Code

#### How should this be manually tested?

1. Open terminal and clone the repo:

    `git clone https://github.com/andela/ah-robotics.git`

2. Change directory into the cloned repository.

    `cd ah-robotics`

3. Checkout to the Chore branch

    `git checkout ft-user-receive-jwt-162949070`

4. Create a virtual environment by running the following commands:

    `virtualenv -p python3 env`

    or

    `python3 -m virtualenv env`

5. Once the virtual environment has been setup, activate it and install the packages required by the project,
    these are contained in the file named `requirements.txt`

      `source env/bin/activate`

      `pip install -r requirements.txt`

### setting up the database

> Ensure PostgreSQL is installed and is running psql, follow these steps to create a new user and a database which will be used in the application.

  1. Start the postgres database server using the command:
  
      `pg_ctl -D /usr/local/var/postgres start`

  2. Run psql interactive terminal

      `psql postgres`

  3. Create a new user:

      `CREATE USER sample_username WITH PASSWORD 'sample_password';`

  4. Grant privileges to the user:

      `ALTER USER sample_username CREATEDB;`

  5. Create a database:

      `CREATE DATABASE sample_database_name WITH OWNER sample_username;`
  6. Create a .env as guided by the .env_example and add the following configuration variables

      ```source-json
      export DB_NAME="database_name"
      export DB_USER="sample_username"
      export DB_PASS="sample_password"
      export DB_HOST="host_name_eg_localhost"
      export DB_PORT="port_number_eg_5432"
      export TIME_DELTA=30
      ```

  7. Source .env to set the configuration variables:

      `source .env`
  8. Run migrations to create the tables in the database:

      ```source-json
      python manage.py makemigrations
      python manage.py migrate
      ```

---

### Run The Server

Once everything has been setup, to run the application run the command:

   `python manage.py runserver`

The application can be accessed in the url <http://localhost:8000>

---

#### What are the relevant pivotal tracker stories?

[#162949070](https://www.pivotaltracker.com/story/show/162949070)

#### Screenshots

<img width="1135" alt="screenshot 2019-01-15 at 17 54 14" src="https://user-images.githubusercontent.com/6994982/51188237-9a35a200-18ee-11e9-94a7-593cd0ea90d5.png">

2019-01-15 15:45 UTC, Paulvitalis200 reviewed
Hey @waracci @jomasim , 
Good work. It is running on my machine. However, please indicate in the Pull Request description that we should exit the psql terminal before we source our .env file.

Regards,
Paul Vitalis

2019-01-15 15:46 UTC, waracci commented
> Hey @waracci @jomasim ,
> Good work. It is running on my machine. However, please indicate in the Pull Request description that we should exit the psql terminal before we source our .env file.
> 
> Regards,
> Paul Vitalis

well noted!

2019-01-15 15:52 UTC, johnwayodi approved these changes
Very good work. Works as expected.

2019-01-15 17:17 UTC, sharkdevs commented
You have done a good work @waracci and @jomasim 
I only suggest that you add a `successful login` message as one of the fields in the output. It will help us give user feedback when consuming the API.

2019-01-15 17:52 UTC, Teatoller commented
Dear @waracci 

I am able to follow the instructions 1-5 under "*How should this be manually tested?*". 
This bit is perfect and easy to follow.

I have also been able to follow the instructions for *setting up database* 1-5 successfully.
```
Database: authors
username: Teatoler
```
<img width="1280" alt="screenshot 2019-01-15 at 20 37 37" src="https://user-images.githubusercontent.com/39020475/51198569-a4af6600-1905-11e9-8363-265b1aae9980.png">

- Instruction 6 was not very clear but I want to think that I figured it out.
- The ```source .env``` was not able to start the activate the virtual environment for me when I ran it on the terminal.

<img width="1280" alt="screenshot 2019-01-15 at 20 23 48" src="https://user-images.githubusercontent.com/39020475/51198751-2f906080-1906-11e9-8c65-c1a058d94204.png">

Kindly check if something could be a missing something out or if a fix is needed to make it easier for an average user.

Regards
Steven Ennis

2019-01-16 03:32 UTC, jomasim commented
> > > Dear @waracci
> > > I am able to follow the instructions 1-5 under "_How should this be manually tested?_".
> > > This bit is perfect and easy to follow.
> > > I have also been able to follow the instructions for _setting up database_ 1-5 successfully.
> > > ```
> > > Database: authors
> > > username: Teatoler
> > > ```
> > > <img alt="screenshot 2019-01-15 at 20 37 37" width="1280" src="https://user-images.githubusercontent.com/39020475/51198569-a4af6600-1905-11e9-8363-265b1aae9980.png">
> > > 
> > > * Instruction 6 was not very clear but I want to think that I figured it out.
> > > * The `source .env` was not able to start the activate the virtual environment for me when I ran it on the terminal.
> > > 
> > > <img alt="screenshot 2019-01-15 at 20 23 48" width="1280" src="https://user-images.githubusercontent.com/39020475/51198751-2f906080-1906-11e9-8c65-c1a058d94204.png">
> > > Kindly check if something could be missing out or if a fix is needed to make it easier for an average user.
> > > Regards
> > > Steven Ennis
> > 
> > 
> > @Teatoller On instruction 5 you were required to activate your virtualenv but it looks like you missed that as I can see on your terminal.  In order to activate your virtualenv run the following command :
> > ```
> > $ source env/bin/activate
> > ```
> > Then export all your variables by running
> > ```
> > $ source  .env
> > ```

2019-01-16 04:32 UTC, waracci commented
> Dear @waracci
> 
> I am able to follow the instructions 1-5 under "_How should this be manually tested?_".
> This bit is perfect and easy to follow.
> 
> I have also been able to follow the instructions for _setting up database_ 1-5 successfully.
> 
> ```
> Database: authors
> username: Teatoler
> ```
> <img alt="screenshot 2019-01-15 at 20 37 37" width="1280" src="https://user-images.githubusercontent.com/39020475/51198569-a4af6600-1905-11e9-8363-265b1aae9980.png">
> 
> * Instruction 6 was not very clear but I want to think that I figured it out.
> * The `source .env` was not able to start the activate the virtual environment for me when I ran it on the terminal.
> 
> <img alt="screenshot 2019-01-15 at 20 23 48" width="1280" src="https://user-images.githubusercontent.com/39020475/51198751-2f906080-1906-11e9-8c65-c1a058d94204.png">
> 
> Kindly check if something could be missing out or if a fix is needed to make it easier for an average user.
> 
> Regards
> Steven Ennis
Thanks Steve for your time to review and provide insightful feedback, we will take it into consideration.

2019-01-16 09:07 UTC, Collins33 commented
@waracci @jomasim I need more clarity on how to test the work you did. The instructions given are for just setting up the branch. More screenshots with the individual ways to actually test the feature for generating the jwt token. This is should be done after the server is started.

2019-01-16 09:17 UTC, waracci commented
> @waracci @jomasim I need more clarity on how to test the work you did. The instructions given are for just setting up the branch. More screenshots with the individual ways to actually test the feature for generating the jwt token. This is should be done after the server is started.

Well noted, working on it.

2019-01-16 09:42 UTC, waracci commented
> @waracci @jomasim I need more clarity on how to test the work you did. The instructions given are for just setting up the branch. More screenshots with the individual ways to actually test the feature for generating the jwt token. This is should be done after the server is started.

@Collins33, we have been able to make the requested changes. Kindly have a look.

2019-01-16 10:05 UTC, Paulstar200 commented
Hello @waracci @jomasim ,
Thank you for adding the postman requirement on the PR

Regards,
Paul Vitalis Otieno

2019-01-16 11:02 UTC, Teatoller commented
Helle @waracci ,

Subsequent to my earlier feedback at the point ```7```  I suggest updating ```.env``` instructions by adding.
``` source env/bin/activate```
This way when the user runs the ```source .env``` on the terminal it will activate the virtual env.

<img width="1280" alt="screenshot 2019-01-16 at 13 04 11" src="https://user-images.githubusercontent.com/39020475/51244216-898c3700-1995-11e9-9f1d-86cc01983c8d.png">

The url you have given http://localhost:8000/ for running the server gives the following image.
Consider suggesting for the user http://localhost:8000/admin/ just so that the don't land on a 404 page. See screenshot.

<img width="1280" alt="screenshot 2019-01-16 at 07 36 14" src="https://user-images.githubusercontent.com/39020475/51244214-898c3700-1995-11e9-9332-4355c91e28fe.png">

Lastly, I have been able to _successfully test in Postman_. **Good work!**.

<img width="1280" alt="screenshot 2019-01-16 at 13 48 20" src="https://user-images.githubusercontent.com/39020475/51244217-898c3700-1995-11e9-83c7-1ae2118bd3d1.png">

2019-01-16 11:04 UTC, waracci commented
> Helle @waracci ,
> 
> Subsequent to my earlier feedback at the point `7` I suggest updating `.env` instructions by adding.
> ` source env/bin/activate`
> This way when the user runs the `source .env` on the terminal it will activate the virtual env.
> 
> <img alt="screenshot 2019-01-16 at 13 04 11" width="1280" src="https://user-images.githubusercontent.com/39020475/51244216-898c3700-1995-11e9-9f1d-86cc01983c8d.png">
> 
> The url you have given http://localhost:8000/ for running the server gives the following image.
> Consider suggesting for the user http://localhost:8000/admin/ just so that the don't land on a 404 page. See screenshot.
> 
> <img alt="screenshot 2019-01-16 at 07 36 14" width="1280" src="https://user-images.githubusercontent.com/39020475/51244214-898c3700-1995-11e9-9332-4355c91e28fe.png">
> 
> Lastly, I have been able to _successfully test in Postman_. **Good work!**.
> 
> <img alt="screenshot 2019-01-16 at 13 48 20" width="1280" src="https://user-images.githubusercontent.com/39020475/51244217-898c3700-1995-11e9-83c7-1ae2118bd3d1.png">

Thanks for the very elaborate review, your feedback is appreciated. 👍

2019-01-16 12:20 UTC, Collins33 commented
Awesome work on the implementation. Testing it on my local machine worked as expected. I, however, would like a small change, since export TIME_DELTA="30" is crucial to the working of the task, you could update the env. example and the readme file

2019-01-16 12:28 UTC, Collins33 requested changes

2019-01-16 12:28 UTC, Collins33 commented on authors/apps/authentication/backends.py
This file contains a lot of spaces. Remove them

2019-01-16 12:39 UTC, waracci commented on authors/apps/authentication/backends.py
I got rid of the extra blank lines and run `pep8` checker on it, all checks are ok.

2019-01-16 12:43 UTC, sharkdevs commented
It is good work especially on how much the tests are cover.

2019-01-16 12:45 UTC, sharkdevs reviewed
It is good work.

2019-01-16 14:16 UTC, Collins33 approved these changes
Nice work. The instructions are clear and it worked perfectly

2019-01-16 14:17 UTC, merged